### ISSUE TITLE
TypeError: Object.defineProperties called on non-object

### ISSUE THREAD

**Issue by matteocrippa** [flatiron/cradle#166]
Using the latest version from npm i'm experiencing this issue when I connect to a local db and I try to create a database.

Here the code used:

``` javascript
db.exists(function(error, exists){
if(error)
 console.log(error);
else if (exists)
 console.log("ok");
else{
db.create();
db.save('_design/test',{
  all: { 
   map: function(doc){
    if(doc.name) emit(doc.name, doc);
   }
}
});
```

Running this code once I receive this error:

/node_modules/cradle/lib/cradle/response.js:126
    return Object.defineProperties(obj, descriptor);
                  ^
TypeError: Object.defineProperties called on non-object
    at Function.defineProperties (native)
    at Object.extend (/node_modules/cradle/lib/cradle/response.js:126:19)
    at Request._callback (/node_modules/cradle/lib/cradle.js:187:18)
    at Request.callback (/node_modules/cradle/node_modules/request/main.js:119:22)
    at Request.<anonymous> (native)
    at Request.emit (events.js:70:17)
    at Request.<anonymous> (/node_modules/cradle/node_modules/request/main.js:521:16)
    at Request.emit (events.js:67:17)
    at IncomingMessage.<anonymous> (/node_modules/cradle/node_modules/request/main.js:483:14)
    at IncomingMessage.emit (events.js:88:20)

**Comment by jcataluna** [comment]
HI, I'm getting the same problem reported on this thread.

* cradle: last from npm
* node: v 4.2.3
* couchdb: v1.6.1

Error stack:

```
/home/jcataluna/devel/testMediaVida/testnoapi/node_modules/cradle/lib/cradle/response.js:133
    return Object.defineProperties(obj, descriptor);
                  ^

TypeError: Object.defineProperties called on non-object
    at Function.defineProperties (native)
    at Object.__dirname.extend (/home/jcataluna/devel/testMediaVida/testnoapi/node_modules/cradle/lib/cradle/response.js:133:19)
    at Request._onResponse [as _callback] (/home/jcataluna/devel/testMediaVida/testnoapi/node_modules/cradle/lib/cradle.js:221:20)
    at Request.init.self.callback (/home/jcataluna/devel/testMediaVida/testnoapi/node_modules/cradle/node_modules/request/request.js:198:22)
    at emitTwo (events.js:87:13)
    at Request.emit (events.js:172:7)
    at Request.<anonymous> (/home/jcataluna/devel/testMediaVida/testnoapi/node_modules/cradle/node_modules/request/request.js:1035:10)
    at emitOne (events.js:82:20)
    at Request.emit (events.js:169:7)
    at IncomingMessage.<anonymous> (/home/jcataluna/devel/testMediaVida/testnoapi/node_modules/cradle/node_modules/request/request.js:962:12)
    at emitNone (events.js:72:20)
    at IncomingMessage.emit (events.js:166:7)
    at endReadableNT (_stream_readable.js:905:12)
    at doNTCallback2 (node.js:441:9)
    at process._tickDomainCallback (node.js:396:17)
```
I'm creating databases dynamically so I really need it working ;)

Regards.

**Comment by Powpow-Shen** [comment]
Hi @jcataluna ,
Would you mind also test with the PR I sent
https://github.com/flatiron/cradle/pull/260

**Comment by deathg0d** [comment]
I had this problem. But for me it turns out that the error was coming from auth before db creation.

**Edit: Never mind.** It isn't the auth. I am trying to dynamically create a new db after checking if it already exists. It worked one time. Now I get the error again. Not sure what's causing this!
