### ISSUE TITLE
db.create() crashes without callback

### ISSUE THREAD

**Issue by mauritslamers** [flatiron/cradle#179]
When performing db.create() without a callback, cradle crashes:

Used: 
- cradle 0.6.3 (npm install)
- nodejs 0.8.1

Trace: 

/.../node_modules/cradle/lib/cradle.js:201
        callback(null, self.options.raw ? body : new cradle.Response(body, res
        ^
TypeError: undefined is not a function
    at Request.cradle.Connection.request [as _callback](/home/maurits/Development/node/ml_backendjs/node_modules/cradle/lib/cradle.js:201:9)
    at Request.init.self.callback (/home/maurits/Development/node/ml_backendjs/node_modules/cradle/node_modules/request/main.js:120:22)
    at Request.EventEmitter.emit (events.js:91:17)
    at Request.<anonymous> (/home/maurits/Development/node/ml_backendjs/node_modules/cradle/node_modules/request/main.js:555:16)
    at Request.EventEmitter.emit (events.js:88:17)
    at IncomingMessage.Request.start.self.req.self.httpModule.request.buffer (/home/maurits/Development/node/ml_backendjs/node_modules/cradle/node_modules/request/main.js:517:14)
    at IncomingMessage.EventEmitter.emit (events.js:115:20)
    at IncomingMessage._emitEnd (http.js:366:10)
    at HTTPParser.parserOnMessageComplete [as onMessageComplete](http.js:149:23)
    at Socket.socketOnData [as ondata](http.js:1356:20)

**Comment by vonKristoff** [comment]
same same .. 

cradle.js:235
        callback(null, self.options.raw ? body : new cradle.Response(body, res
        ^
TypeError: string is not a function
